trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps: 

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.2.104' 
  inputs: 
    version: 2.2.104
  
- task: DotNetCoreCLI@2 
  displayName: 'dotnet restore from feed' 
  inputs: 
    command: restore 
    projects: '$(Parameters.projects)' 
    vstsFeed: '679d4c1d-f66f-49a2-ac93-06e71eb6e4b5/865786bf-d228-4309-a51f-ce69234bc5d2'
    includeNuGetOrg: false 
    versioningScheme: byBuildNumber
 
- task: DotNetCoreCLI@2 
  displayName: 'dotnet build' 
  inputs: 
    projects: '$(Parameters.projects)' 
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(GitVersion.NuGetVersion)' 
    versioningScheme: byBuildNumber
 
- task: DotNetCoreCLI@2
  displayName: 'dotnet pack' 
  inputs: 
    command: pack
    packagesToPack: '$(Parameters.projects)' 
    nobuild: true 
    versioningScheme: byEnvVar 
    versionEnvVar: GitVersion.NuGetVersion

- task: DotNetCoreCLI@2 
  displayName: 'dotnet nuget push' 
  inputs: 
    command: push 
    publishVstsFeed: '679d4c1d-f66f-49a2-ac93-06e71eb6e4b5/865786bf-d228-4309-a51f-ce69234bc5d2'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
    nuGetFeedType: 'internal'